### ISSUE TITLE
Toggle Switch AccentBrush automatically resets to default value

### ISSUE THREAD

**Issue by MaxMichel2** [ratishphilip/wpfspark#12]
As the title implies, when I add a ToggleSwitch to my code, I am unable to change the AccentBrush color. When I do, the color immediately switches back but still shows as if it has been changed in the xaml code.

**Comment by ratishphilip** [comment]
Is the `AccentMode` property set to `System`?
In that case the toggle button will keep reverting to System Accent color if you try to change the `AccentBrush`.

Try setting the `AccentMode` to `User` and then set the `AccentBrush`.

**Comment by MaxMichel2** [comment]
> Is the `AccentMode` property set to `System`?
> In that case the toggle button will keep reverting to System Accent color if you try to change the `AccentBrush`.
> 
> Try setting the `AccentMode` to `User` and then set the `AccentBrush`.

Yep, looking back this was a very dumb question. I even implemented the whole toggle switch myself to see if I could somehow edit parts of it to resolve the issue before finding this option. 

Thanks a lot for the rapid reply!
