### ISSUE TITLE
ToggleSwitch iOS style "Light" specifier

### ISSUE THREAD

**Issue by MHLoppy** [ratishphilip/wpfspark#13]
The [documentation](https://www.codeproject.com/Articles/1060961/WPFSpark-v) for the iOS-style toggle switches says:

> ToggleSwitch.iOS.XXXX.Style - Represents the iOS ToggleButton for light backgrounds where XXXX refers to the accent color.

but it seems the naming for these switches is actually

> ToggleSwitch.iOS **.Light** .<color>.Style

I'm not sure whether it was supposed to be inferred to add the `Light` specifier even in the absence of dark versions of those switches, but it felt quite unintuitive as a novice C# dev!

**Comment by ratishphilip** [comment]
@MHLoppy thanks for pointing it out.
I have fixed the error in the documentation.
