### ISSUE TITLE
Can not add to my project

### ISSUE THREAD

**Issue by IAmOrion** [ratishphilip/wpfspark#16]
I tried to add via the NuGet Manager and get this error:

`Could not install package 'WPFSpark 1.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Any ideas how to fix it?

**Comment by ratishphilip** [comment]
Hi @IAmOrion Please use WPFSpark v1.4 instead of v1.5.
V1.5 targets .net Core 3.1 and .Net 5 whereas v1.4 targets earlier .net frameworks.
