### ISSUE TITLE
No Disposing of ToggleSwitch

### ISSUE THREAD

**Issue by bisato** [ratishphilip/wpfspark#2]
Hello,

the AddValueChanged in the ctor of ToggleSwitch is preventing the disposing of ToggleSwitch.
See [here](http://www.eidias.com/blog/2014/2/13/memory-leak-using-propertydescriptor-addvaluechanged).
I propose to add this to the ctor:

`this.Unloaded += OnUnloaded;`

and then add this method:

> private void OnUnloaded(object sender, RoutedEventArgs routedEventArgs)
> {
>     this.Unloaded -= OnUnloaded;
>     // Unlisten to the BorderThickness changed event to update the layout
>     var dpd = DependencyPropertyDescriptor.FromProperty(BorderThicknessProperty, typeof(ToggleSwitch));
>     dpd?.RemoveValueChanged(this, EventHandler);
> }

**Comment by ratishphilip** [comment]
Done. Thank you.
