### ISSUE TITLE
ToggleSwitch

### ISSUE THREAD

**Issue by mavris** [ratishphilip/wpfspark#4]
Hi,
I am using ToggleSwitch to my project and I notice that you have removed the IsChecked functionality. Is there is any way to initialize the state of the ToggleSwitch with bindings?

**Comment by ratishphilip** [comment]
@mavris ToggleSwitch derives from ToggleButton class and it does have IsChecked property. It is not removed.

**Comment by mavris** [comment]
Sorry, what I meant is that I am binding a boolean to IsChecked and it doesn't affect the UI. I also tried to set it to "false" but it still not working.

**Comment by ratishphilip** [comment]
I just tested your scenario. It seems to be working for me.
Check out the sample project attached below.

[WpfSparkTester2.zip](https://github.com/ratishphilip/wpfspark/files/828482/WpfSparkTester2.zip)

**Comment by mavris** [comment]
It's working thanks. I don't what what went wrong.
