### ISSUE TITLE
Not an issue, more a question

### ISSUE THREAD

**Issue by ergins23** [ratishphilip/wpfspark#6]
The [Wiki](https://wpfspark.wordpress.com/2016/07/11/wpfspark-v1-3-released/) page (and the readme.md file) indicate that the latest version is 1.3, I downloaded the code from here and the version number in AssetmblyInfo.cs is 12.0.1.
Is the code correct or is the Wiki?
Best regards
//*Ergin

**Comment by ratishphilip** [comment]
It is a mistake in the AssemblyInfo.cs file.
The wiki page mentions the right version number.
Will be fixed with the next major release.
