### ISSUE TITLE
Framework 4.6.1 Support

### ISSUE THREAD

**Issue by Sago92** [ratishphilip/wpfspark#7]
Hello,

Do you plan to support .NET Framework 4.6.1 in the future? I would like to use your library for my project.

Regards

**Comment by ratishphilip** [comment]
Hi @Sago92,

wpfspark project currently targets .NET Framework 4.6.2.

Is there any specific reason you want to stay on 4.6.1?

**Comment by Sago92** [comment]
Hello Ratishphilip,

The target Framework of all my projects is 4.6.1, I will try to change it tomorrow. Is there any special reason why 4.6.1 is not included in your library? Do you plan to support 4.7 in the next months?

Regards

**Comment by ratishphilip** [comment]
Earlier it was 4.6.1 then later updated it to 4.6.2 as it was the latest version of .NET.

Yeah there is a plan to support 4.7. Will be adding a nuget this month.

**Comment by Sago92** [comment]
I am a litte bit confused. Why is your package only supporting the largest .NET Framework? When  your library is running under different Framework versions, it would be great if you have the possability to install it under every supported .NET Framework you released. Here is a MSDN topic for this https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

Regards

**Comment by ratishphilip** [comment]
Thanks.

**Comment by ratishphilip** [comment]
@Sago92 
WPFSpark v.14 now supports the following dotNet frameworks
- 4.6
- 4.6.1
- 4.6.2
- 4.7
- 4.7.1
- 4.7.2

The latest version is available in Nuget.
