### ISSUE TITLE
drag n drop between fluid wrap panels

### ISSUE THREAD

**Issue by krunalc** [ratishphilip/wpfspark#8]
Is it possible to drag n drop items between fluid wrap panels? I configured two fluid wrap panels and set AllowDrop on both panels. I can drag the item from one panel to another panel but upon d?ropping item, it is not getting added to other fluid panel. Any help to establish drag n drop between panels.

**Comment by ratishphilip** [comment]
Setting AllowDrop is not enough.
Have a look [here](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control).

**Comment by ratishphilip** [comment]
Closing as the link to enable drag and drop between panels was provided and no further response was obtained.
